using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SurveyReportRE.Migrations
{
    /// <inheritdoc />
    public partial class add_policy_issuance_model : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "PolicyIssuanceRequest",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    dateCreated = table.Column<DateTime>(type: "datetime2", nullable: true),
                    dateModified = table.Column<DateTime>(type: "datetime2", nullable: true),
                    createdByName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    modifiedByName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_confirmedQuotation = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_reason = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_listEmail = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_policyNo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_title2Email = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_productName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_piStatusLabel = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_jogetQuoNum = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_TSremarks = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_piNumByPm = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a3Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a1_flag = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a5DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_typeOfPropertyListAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_holdCover = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_BODApproved = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_FOInchargedView = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_FOIncharged = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_piRemarks = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    c_URFAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a8DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_othersAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a1DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_emailMKTClient = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_piNumHCM1 = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_declarationAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_newReplacementValueAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_assignee = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_premiumBreakdownAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a1Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_languageOfPolicy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_operationYearofFactoriesAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_URF = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_chasisEngineNumberAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_global = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_finalPremium = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_piNumHanoi1 = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_reqDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    c_a8Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_userEmail = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_premiumBreakdown = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_noteForCoInsuranceOutward = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_ichigenka = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_businessChannel = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_emailMKTClientAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_emailInformRI = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_quantityOfPolicy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a4DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a4Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a7DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_declaration = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_piStatus = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_confirmedQuotationAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_listOfMachineriesAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_emailInformRIAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_BODApprovedAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_operationYearofFactories = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a6Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_finalPremiumAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_packageOfPolicy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_coInsuranceOutward = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_policyHolder = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_linkEmail = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_TSIncharged = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_notes = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_subject = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_dueDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    c_sourceOfBusiness = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a2Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_piNum = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_breakdownSIAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_piNumByTs = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_others = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_assigneeForm = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_res = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_chasisEngineNumber = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_nameOfBizChannel = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a6DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_foStatus = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_holdCoverAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a3DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_reqPerson = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_resAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_listOfMachineries = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_RIScheme = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_refNum = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_parent_id = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_dateInsured = table.Column<DateTime>(type: "datetime2", nullable: true),
                    c_reqType = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_RIClosings = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a7Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_TSharged = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_RISchemeAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_noteForCoInsurance = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_typeOfPropertyList = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_fo2Status = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_piRefNum = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_attachment = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_piNumByFo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_KYCCheckedAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_proposalForm = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_piType = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_productType = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_proposalFormAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_ichigenkaAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_globalAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_RIClosingsAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_KYCChecked = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a2DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_newReplacementValue = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_breakdownSI = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_tsStatus = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a5Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_titleEmail = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_remarks = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_tdyDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    c_preMKTTS = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_preRemark = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    c_prePIC = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_pmRemarks = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    c_dateFOTS = table.Column<DateTime>(type: "datetime2", nullable: true),
                    c_piLocation = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_SLAPolicyNo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_SLAReqType = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_addiEmailCc = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_addiAttachments = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_preAddiEmailCc = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    Guid = table.Column<Guid>(type: "uniqueidentifier", nullable: false, defaultValueSql: "NEWID()"),
                    CreatedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true, defaultValueSql: "GETDATE()"),
                    ModifiedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Deleted = table.Column<bool>(type: "bit", nullable: false, defaultValueSql: "0"),
                    DeletedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    RowOrder = table.Column<long>(type: "bigint", nullable: true),
                    CopyFromGuid = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    DraftGuid = table.Column<Guid>(type: "uniqueidentifier", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PolicyIssuanceRequest", x => x.Id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PolicyIssuanceRequest");
        }
    }
}
