using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SurveyReportRE.Migrations
{
    /// <inheritdoc />
    public partial class maintenance_more_tables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "PolicyIssuanceProcess",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    dateCreated = table.Column<DateTime>(type: "datetime2", nullable: true),
                    dateModified = table.Column<DateTime>(type: "datetime2", nullable: true),
                    createdByName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    modifiedByName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_PMPIC = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_listEmail = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_noteForCoInsurance = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_title2Email = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_policyNo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_userAccept = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_acceptedDate = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_piStatusLabel = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_piRefNum = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_jogetQuoNum = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_MKTTS = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_piNumByPm = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_userEmail = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_piType = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_productType = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a1_flag = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_foStatus = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_completedDate = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_piStatus = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_foUname = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_pmStatus = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_refNum = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a1DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_parent_id = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_tsStatus = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_reqType = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_assignee = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_PM = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_titleEmail = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_coInsuranceOutward = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_remarks = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_linkEmail = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_policyHolder = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_FOIncharged = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_pmRemarks = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    c_TSIncharged = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_policyType = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_piAttach = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_quoNumFlag = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_dueDate = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_businessChannel = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_nameOfBizChannel = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_periodInsStart = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_jogetQuoNum1 = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_preRemark = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    c_piRefNumTs = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_status = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_ts = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_qwq = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a2Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a3Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a5DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a6DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a3DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a8DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a1Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a7Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a8Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a4DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a4Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a7DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a2DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a6Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a5Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_prePIC = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_prePm = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_productName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_showNameBizForm = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_dateFOTS = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_preRemarks = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    c_emailCC = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_piNumByTs = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_piNumByFo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_piLocation = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_addiAttachments = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_addiEmailCc = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_preAddiEmailCc = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_followUp = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_preMKTTS = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_numOfPolicy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_field69 = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_TS_remarks = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_hardSoftCopy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    Guid = table.Column<Guid>(type: "uniqueidentifier", nullable: false, defaultValueSql: "NEWID()"),
                    CreatedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true, defaultValueSql: "GETDATE()"),
                    ModifiedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Deleted = table.Column<bool>(type: "bit", nullable: false, defaultValueSql: "0"),
                    DeletedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    RowOrder = table.Column<long>(type: "bigint", nullable: true),
                    CopyFromGuid = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    DraftGuid = table.Column<Guid>(type: "uniqueidentifier", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PolicyIssuanceProcess", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "QuotationProcess",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    dateCreated = table.Column<DateTime>(type: "datetime2", nullable: true),
                    dateModified = table.Column<DateTime>(type: "datetime2", nullable: true),
                    createdByName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    modifiedByName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_reason = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_attachmentQT = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_listEmail = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_RIArrangementAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_policyNo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_qtNum = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_totalPremiumBI = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_reasonForReferralReasons = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_lawJurisEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a1_flag = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a5DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_reqResNo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_actualDays = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_stocksEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_excRate = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_authUwForm = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a8DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_totalSumIns = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_exposure = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_locationsEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_subformID = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_lossHisAccNoClaim = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_preDiscountCom = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a1Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_TMIVShare = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_equivalentTo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_authUw = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_installmentGrid = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_nonAppetiteRisk = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_reqDate = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_annualVoluntaryPremium = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a8Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_currency = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_claimSetBasisViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_retention = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_termsConEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_totalPremium = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a4Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_reqResNoSel = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_insNameViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_qtStatusLabel = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_attQuo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_actualDaysBi = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_typeOfReferral = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_geoLimitEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_nameClause = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_tsiFromBi = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_phNameEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_linkEmail = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_country = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_qtNumSel = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_notes = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_tariffCode = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_VATPerc = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_mgrTs = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_dueDate = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_netRetention = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_insIntSumViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_treatySurplus = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_topRiskPd = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_mktTsStatus = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_registeredAddress = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_quoValEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_phNameViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_others = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_addExtEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_bIQuo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a6DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_comPremium = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_periodInsStart = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a3DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_dutyDisViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_cloneResForm = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_reasonForReferralYN = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_proCusViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_addInsEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_annualCFEPremium = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_installment = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_totalAnnualPremium = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_CoOut = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_BIQtNum = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_policyDecViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_volPremium = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_MKTFront = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_typeOfPropertyList = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_preDiscountVol = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_decvalue = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_attachSub = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_authUwCond = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_resForm = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_currentInsurer = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_mktFoRemarks = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    c_locationsViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_proOpenAreaViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_excRateTotalSumInsVND = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_coverage = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_stocksViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_preDiscount = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_tsiFromBiForm = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_coverageInViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_nonAppetiteRiskBool = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_insIntSumEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_periodAlertFlag = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_VATPercBI = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_proOpenAreaEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_proCusEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_management = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_VATAmountBI = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_location = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a5Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_clientNameViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_titleEmail = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_premiumDis = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_topRiskPdBi = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_occupation = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_VAT = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_premiumRate = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_discount = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_title2Email = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_insNameEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_productName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_insRegAdd = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_showCFE = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_jogetQuoNum = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_VATAmount = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_srAddNote = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    c_oriReqType = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_voluntary = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_incBIQuo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_noteForBrokerViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a3Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_surveyResultAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_mktTsRemarks = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    c_qtStatus = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_MKTCommentProp = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    c_UWComments = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    c_oriNum = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_topRiskPdQt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_tmiCode = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_termsConViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_showBiQuotForm = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_excRateTotalSumIns = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_lawJurisViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_periodInsEnd = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_dutyDisEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_foUname = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_uwAccept = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_premiumRateBI = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a1DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_typeOfQT = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_uwAcceptDate = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_otherAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_totalSumInsVND = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_totalDue = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_showQuotForm = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_protection = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_moreInfo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_capacity = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_insuredProperty = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_quoValViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_TSIPdQt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_geoLimitViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_actualPremium = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_businessChannel = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_addExtViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_legalStatusViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_capacityBool = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_inslabel = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_coverageInEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_businessOccupationEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a4DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_attachResForm = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_attachRes = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a7DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_claimSetBasisEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_insvalue = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_preMKTTS = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a6Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_surveyResultBool = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_numLocation = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_TSIPdBi = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_policyHolder = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_mapLocation = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_annualPremium = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_MKTAuthority = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_lossHisAcc = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_mktTs = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_sourceOfBusiness = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_businessOccupation = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_indPeriod = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_annualRate = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_insRegAddViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_referUW = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_phRegisteredAddressEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a2Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_addInsViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_actualDaysCalcBi = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_percentage = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_tariffRate = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_totalSumInsUSD = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_lossHisAccPremium = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_quarDecSumViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_businessOccupationViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_actualDaysCalc = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_specApplied = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_lossHisAccAmtLoss = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_limitLia = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_totalSumInsBI = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_mgrUname = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_nameOfBizChannel = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_incIARQuo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_registeredAddressViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_TSI = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_quotationBI = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_UWCommentsAtt = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    c_refNum = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_parent_id = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_reqType = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_riskGrade = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_preDiscountTotal = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_legalStatusEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a7Days = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_code = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_qrNum = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_insPeriod = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_topRisk = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a5_flag = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_policyDecEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_attachment = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_quarDecSumEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_uwUname = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_sftpStatus = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_noteForBroker = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_construction = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_phRegisteredAddressViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_cloneResFlag = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_IARQuoNum = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_showGrade = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_termsCon = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_amount = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_operationYearOfRisk = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_declabel = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_a2DaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_ins = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_lossHisAccRatio = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_attachLocation = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_deductible = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_RIArrangement = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_TSIPd = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_surveyResult = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_insRegAddEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_resReqDate = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_typeOfGrade = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_resAtt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_quotationNo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_showBiQuot = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_mksTsStatus = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_showQuot = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_indPeriodAlertFlag = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_indPeriodAlert = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_insBool = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_preRateAlertFlag = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_BIQtNumView = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_sourceOfBusinessView = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_quoNumView = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_isCfe = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_productNameView = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_policyHolderView = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_tmiCodeView = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_testb = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_testa = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_subject = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_mktFoStatus = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_tempMktTs = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_countLoca = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_atLink = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_at = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_datetime = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_test11111 = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_emailCc = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_status = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_showMGR = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_preUw = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_field2 = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_idVIew = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_idEdit = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_reqDateQT = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_lineName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_showNameBizForm = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_mgrUnamePast = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_uwUnamePast = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_mktTsUnamePast = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_insBoolBi = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_dateTS = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_dateTSAccept = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_dateTSComplete = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_dateFORouteUW = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_dateUWAccept = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_dateUWComplete = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_dateFORouteMNG = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_dateFORevise = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_dateFOComplete = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_userTSSubmit = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_userUWAccept = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_cfePremium = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_voluntaryPremium = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_totalPremiumBeforeVat = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_countLocaBI = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_sumInsCurrencyBI = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_exRateVND = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_field27 = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_field28 = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_quotationLocation = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_field166 = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_field47 = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_uwLeader = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_dateUWLComplete = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_uwFormFlag = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_totalLocaActual = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_totalLocaAnnual = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_uwLeaderUname = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_skipWf = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_addiEmailCc = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_reqTypeForm = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_addiAttachments = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_preAddiEmailCc = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_reqPerson = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_piType = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_clientCodeJG = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_businessAddressViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_clientNameEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_clientCodePA = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_businessAddressEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_refId = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_numOfQuot = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_uwDecisions = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_reinsurrance = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_foReins = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    Guid = table.Column<Guid>(type: "uniqueidentifier", nullable: false, defaultValueSql: "NEWID()"),
                    CreatedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true, defaultValueSql: "GETDATE()"),
                    ModifiedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Deleted = table.Column<bool>(type: "bit", nullable: false, defaultValueSql: "0"),
                    DeletedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    RowOrder = table.Column<long>(type: "bigint", nullable: true),
                    CopyFromGuid = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    DraftGuid = table.Column<Guid>(type: "uniqueidentifier", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_QuotationProcess", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "QuotationRequest",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    dateCreated = table.Column<DateTime>(type: "datetime2", nullable: true),
                    dateModified = table.Column<DateTime>(type: "datetime2", nullable: true),
                    createdByName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    modifiedByName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_VAT = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_premiumRate = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_policyNo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_productName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_insViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_insRegAdd = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_jogetQuoNum = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_MKTTS = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_coverageViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_incBIQuo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_noteForBrokerViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_lawJurisEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_mktTsRemarks = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    c_qtStatus = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_actualDays = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_mktTsDaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_stocksEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_excRate = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_tmiCode = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_reqDays = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_lawJurisViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_periodInsEnd = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_dutyDisEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_mktFoDaysSla = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_totalSumIns = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_locationsEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_typeOfQT = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_status = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_typeOfQR = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_TMIVShare = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_uwRa = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_totalDue = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_clientCodePA = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_FOremarks = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_insuredProperty = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_reqDate = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_quoValViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_policyHolderViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_currency = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_geoLimitViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_claimSetBasisViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_businessChannel = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_addExtViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_businessAddressEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_businessOccupationEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_qrStatusLabel = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_claimSetBasisEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_qrStatus = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_reqEmail = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_attQuo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_mktTsDaysSla = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_reqDaysSla = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_numLocation = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_geoLimitEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_to = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_policyHolder = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_mapLocation = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_qtNumSel = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_subject = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_mktFoDaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_dueDate = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_VATPerc = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_sourceOfBusiness = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_businessOccupation = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_insIntSumViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_insRegAddViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_reqDaysOver = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_registeredAddress = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_addInsViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_clientCodeJG = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_quoValEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_quarDecSumViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_businessOccupationViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_addExtEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_nameOfBizChannel = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_clientNameEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_registeredAddressViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_reqPerson = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_clientNameEngSel = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_periodInsStart = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_dutyDisViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_refNum = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_mktFoDays = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_proCusViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_addInsEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_FOremarks1 = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_riskGrade = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_policyDecViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_qrNum = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_insPeriod = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_policyDecEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_quarDecSumEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_locationsViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_noteForBroker = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_proOpenAreaViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_qrNumSel = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_coverage = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_termsCon = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_stocksViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_insIntSumEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_proOpenAreaEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_ins = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_proCusEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_mktTsDays = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_attachLocation = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_deductible = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_location = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_remarks = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_businessAddressViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_test = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_draftBool = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_clientNameEngSelDraft = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_qrNumSelDraft = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_qrNumSelFlag = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_clientNameEngSelFlag = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_quotationLocation = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_addiEmailCc = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_addiAttachments = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    c_notes = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    Guid = table.Column<Guid>(type: "uniqueidentifier", nullable: false, defaultValueSql: "NEWID()"),
                    CreatedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true, defaultValueSql: "GETDATE()"),
                    ModifiedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Deleted = table.Column<bool>(type: "bit", nullable: false, defaultValueSql: "0"),
                    DeletedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    RowOrder = table.Column<long>(type: "bigint", nullable: true),
                    CopyFromGuid = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    DraftGuid = table.Column<Guid>(type: "uniqueidentifier", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_QuotationRequest", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "RecordWorkflow",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    ProcessId = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ActivityId = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    Name = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    RecordGuid = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    Guid = table.Column<Guid>(type: "uniqueidentifier", nullable: false, defaultValueSql: "NEWID()"),
                    CreatedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true, defaultValueSql: "GETDATE()"),
                    ModifiedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Deleted = table.Column<bool>(type: "bit", nullable: false, defaultValueSql: "0"),
                    DeletedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    RowOrder = table.Column<long>(type: "bigint", nullable: true),
                    CopyFromGuid = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    DraftGuid = table.Column<Guid>(type: "uniqueidentifier", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RecordWorkflow", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "ReinsurranceQuarterly",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    No = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    CategoryOfProcess = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    ClientName = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    LineOfBusiness = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    PolicyNo = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    NBRNEN = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    PeriodFrom = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    UWPIC = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    Address = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    Guid = table.Column<Guid>(type: "uniqueidentifier", nullable: false, defaultValueSql: "NEWID()"),
                    CreatedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true, defaultValueSql: "GETDATE()"),
                    ModifiedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Deleted = table.Column<bool>(type: "bit", nullable: false, defaultValueSql: "0"),
                    DeletedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    RowOrder = table.Column<long>(type: "bigint", nullable: true),
                    CopyFromGuid = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    DraftGuid = table.Column<Guid>(type: "uniqueidentifier", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ReinsurranceQuarterly", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "SystemProperties",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    processDefId = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    activityDefId = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    packageId = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ouid = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    type = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    formId = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    formUrl = table.Column<string>(type: "nvarchar(2000)", maxLength: 2000, nullable: true),
                    formIFrameStyle = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    autoContinue = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    jsonProperties = table.Column<string>(type: "nvarchar(max)", maxLength: 8000, nullable: true),
                    tableName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    formOrflowName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    Id1 = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    Id2 = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    Name1 = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    Name2 = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ouidDescription = table.Column<string>(type: "nvarchar(4000)", maxLength: 4000, nullable: true),
                    Guid = table.Column<Guid>(type: "uniqueidentifier", nullable: false, defaultValueSql: "NEWID()"),
                    CreatedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true, defaultValueSql: "GETDATE()"),
                    ModifiedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Deleted = table.Column<bool>(type: "bit", nullable: false, defaultValueSql: "0"),
                    DeletedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    RowOrder = table.Column<long>(type: "bigint", nullable: true),
                    CopyFromGuid = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    DraftGuid = table.Column<Guid>(type: "uniqueidentifier", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SystemProperties", x => x.Id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PolicyIssuanceProcess");

            migrationBuilder.DropTable(
                name: "QuotationProcess");

            migrationBuilder.DropTable(
                name: "QuotationRequest");

            migrationBuilder.DropTable(
                name: "RecordWorkflow");

            migrationBuilder.DropTable(
                name: "ReinsurranceQuarterly");

            migrationBuilder.DropTable(
                name: "SystemProperties");
        }
    }
}
