using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SurveyReportRE.Migrations
{
    /// <inheritdoc />
    public partial class policyissuance_add_model : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // migrationBuilder.DropTable(
            //     name: "Quotation");

            migrationBuilder.CreateTable(
                name: "PolicyIssuance",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    IssueReqNo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    IssueReqRefNo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ParentRequestId = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    RequestType = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    IssueRequestCategory = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    RequestDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DueDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    QuotationCode = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    QuotationCodeAlt = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    QuotationId = table.Column<long>(type: "bigint", nullable: true),
                    PolicyNo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    PolicyHolderId = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    PolicyType = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ProductCode = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ProductType = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    PolicyLanguage = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    PolicyPackage = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    PolicyPeriodStartDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    InsuredDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    PolicyQuantity = table.Column<int>(type: "int", nullable: true),
                    IssueStatusCode = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    IssueStatusLabel = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    OverallStatusCode = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    Subject = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    Notes = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    Reason = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    Remarks = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    PrevRemarks = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    PmRemarks = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    TsRemarks = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    FollowUpNote = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    RiScheme = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    RiClosings = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ReinsuranceType = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    CoInsuranceOutward = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    CoInsuranceNote = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    CoInsurerName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    FinalPremium = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    PremiumBreakdown = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    IsKycChecked = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    DeclarationText = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    URF = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    IsBodApproved = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    HoldCoverType = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    MachineryList = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    PropertyTypeList = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    FactoryOperationYears = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ChassisEngineNumber = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    NewReplacementValue = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    SumInsuredBreakdown = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    IsGlobalCover = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    PolicyLocation = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    Guid = table.Column<Guid>(type: "uniqueidentifier", nullable: false, defaultValueSql: "NEWID()"),
                    CreatedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true, defaultValueSql: "GETDATE()"),
                    ModifiedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Deleted = table.Column<bool>(type: "bit", nullable: false, defaultValueSql: "0"),
                    DeletedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    RowOrder = table.Column<long>(type: "bigint", nullable: true),
                    CopyFromGuid = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    DraftGuid = table.Column<Guid>(type: "uniqueidentifier", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PolicyIssuance", x => x.Id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PolicyIssuance");

            migrationBuilder.CreateTable(
                name: "Quotation",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    AnnualRate = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    BusinessAddress = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    BusinessChannelDisplayName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    BusinessChannelName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    CfeCode = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ClaimSettlementBasisText = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ClauseName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ClientCodeJG = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ClientCodePA = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ClientId = table.Column<long>(type: "bigint", nullable: true),
                    ClientName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    CoInsuranceOutValue = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    CoInsuranceShareValue = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    CoInsurerName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    CopyFromGuid = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true, defaultValueSql: "GETDATE()"),
                    CurrencyCode = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    Deductible = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    DeductibleFire = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    Deleted = table.Column<bool>(type: "bit", nullable: false, defaultValueSql: "0"),
                    DeletedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DiscountPercentOrValue = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    DraftGuid = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    DueDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DutyOfDisclosureText = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    EquivalentToCurrency = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    EvaluationDetailPictureRef = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    EvaluationDetailText = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    EvaluationTotalScore = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    ExchangeRate = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    ExchangeRateTotalSumIns = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    ExchangeRateTotalSumInsVnd = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    Exposure = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    GeoLimitEng = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    GeoLimitViet = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    Guid = table.Column<Guid>(type: "uniqueidentifier", nullable: false, defaultValueSql: "NEWID()"),
                    IarQuotationNo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    InsuredId = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    InsuredName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    IsCfe = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    IsCfeForm = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    JurisdictionLawText = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    LimitOfLiability = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    LineName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    LocationAttachmentRef = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    LocationCountActual = table.Column<int>(type: "int", nullable: true),
                    LocationCountActualAlt = table.Column<int>(type: "int", nullable: true),
                    LocationCountAnnual = table.Column<int>(type: "int", nullable: true),
                    LocationCountDeclared = table.Column<int>(type: "int", nullable: true),
                    LocationCountLegacy = table.Column<int>(type: "int", nullable: true),
                    LocationMapRef = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    LocationSituation = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    LocationSubAttachmentRef = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    LocationSummary = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    LossHistoryAccLossAmount = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    LossHistoryAccNoClaimText = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    LossHistoryAccPremium = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    LossHistoryAccRatio = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    LossHistoryAccText = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    LossHistoryLossAmount = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    LossHistoryLossRatio = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    LossHistoryNoClaimText = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    LossHistoryPremium = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    MktAuthorityFormRef = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    MktAuthorityText = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ModifiedBy = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    NetRetentionValue = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    PIC = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    PartyMultiLangJson = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    PolicyHolderId = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    PolicyHolderName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    PreDiscount = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    PreDiscountCommission = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    PreDiscountTotal = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    PreDiscountVoluntary = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    PremiumActual = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    PremiumAnnual = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    PremiumAnnualTotal = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    PremiumCfe = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    PremiumCfeAnnual = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    PremiumCommission = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    PremiumDiscount = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    PremiumRate = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    PremiumRateAlt = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    PremiumRateBI = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    PremiumTotal = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    PremiumTotalBI = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    PremiumTotalBeforeVat = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    PremiumVoluntary = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    PremiumVoluntaryAnnual = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    PremiumVoluntaryValue = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    ProductCode = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ProductDisplayName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ProductId = table.Column<long>(type: "bigint", nullable: true),
                    ProductName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ProductType = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    QuotationCode = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    QuotationLocationCount = table.Column<int>(type: "int", nullable: true),
                    QuotationStatus = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    QuotationType = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ReferralReasonsText = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ReferralRequiredFlag = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    ReferralType = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    RegisteredAddress = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    RequestNo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    RequestRefNo = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    RequestType = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    RequestedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    RetentionValue = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    RiArrangementAttachmentRef = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    RiArrangementText = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    RiskGrade = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    RiskGradeTableJson = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    RiskGradeType = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    RiskGradingText = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    RowOrder = table.Column<long>(type: "bigint", nullable: true),
                    ShowCfe = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    SourceOfBusinessName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    SpecialAppliedSpec = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    StageAccount = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    StageDept = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    SubLineName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    SumInsuredBI = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    SumInsuredTotal = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    SumInsuredTotalAlt = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    SumInsuredTotalUsd = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    SumInsuredTotalVnd = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    TermsConditionsText = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    TermsMultiLangJson = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    TopRisk = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    TopRiskPd = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    TopRiskPdBI = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    TopRiskPdQuotation = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    TotalDue = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    TreatySurplusValue = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    TsiBI = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    TsiFromBi = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    TsiFromBiForm = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    TsiPd = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    TsiPdBI = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    TsiPdQuotation = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    TsiTotal = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    UwAcceptedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UwAcceptedFlag = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwAccumulatedMetric = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwAnnualMetric = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwAssessorName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwAttachmentRef = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwAuthorityConditionsText = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwAuthorityFormRef = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwAuthorityText = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwBusinessStartedYearOrDate = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwCommentText = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    UwCommentsAttachmentRef = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    UwEilrAtExpiryMetric = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwEvaluationDetailPictureRef = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwEvaluationDetailText = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwEvaluationTotalScore = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    UwFormFlag = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwJapaneseNonJapaneseCode = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwLeaderName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwLeaderUsername = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwLineOfBusinessText = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwLossRatioAccumulatedMetric = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwMktCommentText = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: true),
                    UwOccupationText = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwPolicyHolderText = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwPortfolioName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwPricingPictureRef = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwPricingText = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwReferralReasonText = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwReferralType = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwRelatedFilesRef = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwSourceName = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwSumInsLimitText = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    UwSumInsPictureRef = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    VatAmount = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    VatAmountBI = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    VatFlagOrValue = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    VatPercent = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    VatPercentBI = table.Column<decimal>(type: "decimal(28,9)", nullable: true),
                    WorkflowStatus = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Quotation", x => x.Id);
                });
        }
    }
}
